export const GET_MOVIE_DETAILS='GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS='GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAIL='GET_MOVIE_DETAILS_FAIL';
export const GET_MOVIE_VIDEO='GET_MOVIE_VIDEO';
export const GET_MOVIE_VIDEO_SUCCESS='GET_MOVIE_VIDEO_SUCCESS';
export const GET_MOVIE_VIDEO_FAIL='GET_MOVIE_VIDEO_FAIL';
