export const GET_ALL_MOVIES='GET_ALL_MOVIES';
export const GET_ALL_MOVIES_SUCCESS='GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAIL='GET_ALL_MOVIES_FAIL';
export const GET_SEARCH_TEXT='GET_SEARCH_TEXT';
